### ISSUE TITLE
Cannot build with monero v0.13.0.2

### ISSUE THREAD

**Issue by normoes** [moneroexamples/onion-monero-blockchain-explorer#147]
**Update**:

I eventually used the `devel` branch.
Nevertheless, I stopped trying for now.

See my comment, which starts like

> So, this is where I stop, no clue.

---

I get the error, that `RCTTypeSimpleBulletproof` as well as `RCTTypeFullBulletproof` don't exist.
They appear in `src/tools.cpp`.

I changed them to the according one (``RCTTypeBulletproof``) from the monero source (`src/ringct/rctTypes.h`). 
The complete changed line:
```c++
case rct::RCTTypeBulletproof:
         amount = rct::decodeRct(rv,
                       rct::sk2rct(scalar1),
                       i,
                       mask,
                       hw::get_device("default"));
         break;
```

Not sure, whether that makes sense at all...

After that I still get an error:
```c++
Scanning dependencies of target myxrm
[  5%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
[ 10%] Building CXX object src/CMakeFiles/myxrm.dir/tools.cpp.o
/data/onion-monero-blockchain-explorer/src/tools.cpp: In function 'std::__cxx11::string xmreg::decrypt(const string&, const secret_key&, bool)':
/data/onion-monero-blockchain-explorer/src/tools.cpp:1044:57: error: no matching function for call to 'generate_chacha_key(const secret_key*, long unsigned int, crypto::chacha_key&)'
     crypto::generate_chacha_key(&skey, sizeof(skey), key);
                                                         ^
In file included from /data/monero/src/serialization/crypto.h:37:0,
                 from /data/monero/src/cryptonote_basic/cryptonote_basic.h:44,
                 from /data/monero/src/cryptonote_basic/cryptonote_basic_impl.h:33,
                 from /data/monero/src/cryptonote_core/tx_pool.h:44,
                 from /data/onion-monero-blockchain-explorer/src/monero_headers.h:24,
                 from /data/onion-monero-blockchain-explorer/src/tools.h:18,
                 from /data/onion-monero-blockchain-explorer/src/tools.cpp:5:
/data/monero/src/crypto/chacha.h:73:15: note: candidate: void crypto::generate_chacha_key(const void*, size_t, crypto::chacha_key&, uint64_t)
   inline void generate_chacha_key(const void *data, size_t size, chacha_key& key, uint64_t kdf_rounds) {
               ^~~~~~~~~~~~~~~~~~~
/data/monero/src/crypto/chacha.h:73:15: note:   candidate expects 4 arguments, 3 provided
/data/monero/src/crypto/chacha.h:91:15: note: candidate: void crypto::generate_chacha_key(std::__cxx11::string, crypto::chacha_key&, uint64_t)
   inline void generate_chacha_key(std::string password, chacha_key& key, uint64_t kdf_rounds) {
               ^~~~~~~~~~~~~~~~~~~
/data/monero/src/crypto/chacha.h:91:15: note:   no known conversion for argument 1 from 'const secret_key* {aka const epee::mlocked<tools::scrubbed<crypto::ec_scalar> >*}' to 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}'
src/CMakeFiles/myxrm.dir/build.make:86: recipe for target 'src/CMakeFiles/myxrm.dir/tools.cpp.o' failed
make[2]: *** [src/CMakeFiles/myxrm.dir/tools.cpp.o] Error 1
CMakeFiles/Makefile2:254: recipe for target 'src/CMakeFiles/myxrm.dir/all' failed
make[1]: *** [src/CMakeFiles/myxrm.dir/all] Error 2
```

**Comment by normoes** [comment]
I had another look at the monero sources and found that there is an additional parameter (`kdf_rounds`) to `generate_cacha_key`.

I added this in `tools.cpp` and got a little bit further.

Now, there is another problem:
```c++
Scanning dependencies of target myxrm
[  5%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
[ 10%] Building CXX object src/CMakeFiles/myxrm.dir/tools.cpp.o
[ 15%] Building CXX object src/CMakeFiles/myxrm.dir/CmdLineOptions.cpp.o
[ 20%] Building CXX object src/CMakeFiles/myxrm.dir/rpccalls.cpp.o
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp: In member function 'bool xmreg::rpccalls::get_dynamic_per_kb_fee_estimate(uint64_t, uint64_t&, std::__cxx11::string&)':
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:278:29: error: 'COMMAND_RPC_GET_PER_KB_FEE_ESTIMATE' was not declared in this scope
     epee::json_rpc::request<COMMAND_RPC_GET_PER_KB_FEE_ESTIMATE::request>
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:278:73: error: template argument 1 is invalid
     epee::json_rpc::request<COMMAND_RPC_GET_PER_KB_FEE_ESTIMATE::request>
                                                                         ^
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:280:30: error: the value of 'COMMAND_RPC_GET_PER_KB_FEE_ESTIMATE' is not usable in a constant expression
     epee::json_rpc::response<COMMAND_RPC_GET_PER_KB_FEE_ESTIMATE::response, std::string>
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:278:29: note: 'COMMAND_RPC_GET_PER_KB_FEE_ESTIMATE' was not declared 'constexpr'
     epee::json_rpc::request<COMMAND_RPC_GET_PER_KB_FEE_ESTIMATE::request>
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:280:88: error: wrong number of template arguments (1, should be 2)
     epee::json_rpc::response<COMMAND_RPC_GET_PER_KB_FEE_ESTIMATE::response, std::string>
                                                                                        ^
In file included from /data/monero/contrib/epee/include/net/http_server_handlers_map2.h:30:0,
                 from /data/monero/contrib/epee/include/storages/http_abstract_invoke.h:34,
                 from /data/onion-monero-blockchain-explorer/src/monero_headers.h:22,
                 from /data/onion-monero-blockchain-explorer/src/rpccalls.h:9,
                 from /data/onion-monero-blockchain-explorer/src/rpccalls.cpp:5:
/data/monero/contrib/epee/include/net/jsonrpc_structs.h:52:12: note: provided for 'template<class t_param, class t_error> struct epee::json_rpc::response'
     struct response
            ^~~~~~~~
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:284:11: error: request for member 'jsonrpc' in 'req_t', which is of non-class type 'int'
     req_t.jsonrpc = "2.0";
           ^~~~~~~
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:285:11: error: request for member 'id' in 'req_t', which is of non-class type 'int'
     req_t.id = epee::serialization::storage_entry(0);
           ^~
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:286:11: error: request for member 'method' in 'req_t', which is of non-class type 'int'
     req_t.method = "get_fee_estimate";
           ^~~~~~
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:287:11: error: request for member 'params' in 'req_t', which is of non-class type 'int'
     req_t.params.grace_blocks = grace_blocks;
           ^~~~~~
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:310:20: error: request for member 'result' in 'resp_t', which is of non-class type 'int'
         if (resp_t.result.status == CORE_RPC_STATUS_BUSY)
                    ^~~~~~
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:314:25: error: request for member 'result' in 'resp_t', which is of non-class type 'int'
         else if (resp_t.result.status != CORE_RPC_STATUS_OK)
                         ^~~~~~
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:316:26: error: request for member 'result' in 'resp_t', which is of non-class type 'int'
             err = resp_t.result.status;
                          ^~~~~~
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:333:18: error: request for member 'result' in 'resp_t', which is of non-class type 'int'
     fee = resp_t.result.fee;
                  ^~~~~~
In file included from /data/monero/contrib/epee/include/storages/http_abstract_invoke.h:32:0,
                 from /data/onion-monero-blockchain-explorer/src/monero_headers.h:22,
                 from /data/onion-monero-blockchain-explorer/src/rpccalls.h:9,
                 from /data/onion-monero-blockchain-explorer/src/rpccalls.cpp:5:
/data/monero/contrib/epee/include/storages/portable_storage_template_helper.h: In instantiation of 'bool epee::serialization::store_t_to_json(t_struct&, std::__cxx11::string&, size_t, bool) [with t_struct = const int; std::__cxx11::string = std::__cxx11::basic_string<char>; size_t = long unsigned int]':
/data/monero/contrib/epee/include/storages/http_abstract_invoke.h:44:41:   required from 'bool epee::net_utils::invoke_http_json(boost::string_ref, const t_request&, t_response&, t_transport&, std::chrono::milliseconds, boost::string_ref) [with t_request = int; t_response = int; t_transport = epee::net_utils::http::http_simple_client_template<epee::net_utils::blocked_mode_client>; boost::string_ref = boost::basic_string_ref<char, std::char_traits<char> >; std::chrono::milliseconds = std::chrono::duration<long int, std::ratio<1l, 1000l> >]'
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:302:60:   required from here
/data/monero/contrib/epee/include/storages/portable_storage_template_helper.h:65:14: error: request for member 'store' in 'str_in', which is of non-class type 'const int'
       str_in.store(ps);
       ~~~~~~~^~~~~
/data/monero/contrib/epee/include/storages/portable_storage_template_helper.h: In instantiation of 'bool epee::serialization::load_t_from_json(t_struct&, const string&) [with t_struct = int; std::__cxx11::string = std::__cxx11::basic_string<char>]':
/data/monero/contrib/epee/include/storages/http_abstract_invoke.h:69:45:   required from 'bool epee::net_utils::invoke_http_json(boost::string_ref, const t_request&, t_response&, t_transport&, std::chrono::milliseconds, boost::string_ref) [with t_request = int; t_response = int; t_transport = epee::net_utils::http::http_simple_client_template<epee::net_utils::blocked_mode_client>; boost::string_ref = boost::basic_string_ref<char, std::char_traits<char> >; std::chrono::milliseconds = std::chrono::duration<long int, std::ratio<1l, 1000l> >]'
/data/onion-monero-blockchain-explorer/src/rpccalls.cpp:302:60:   required from here
/data/monero/contrib/epee/include/storages/portable_storage_template_helper.h:48:18: error: request for member 'load' in 'out', which is of non-class type 'int'
       return out.load(ps);
              ~~~~^~~~
make[2]: *** [src/CMakeFiles/myxrm.dir/rpccalls.cpp.o] Error 1
src/CMakeFiles/myxrm.dir/build.make:134: recipe for target 'src/CMakeFiles/myxrm.dir/rpccalls.cpp.o' failed
CMakeFiles/Makefile2:254: recipe for target 'src/CMakeFiles/myxrm.dir/all' failed
make[1]: *** [src/CMakeFiles/myxrm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by normoes** [comment]
So, this is where I stop, no clue.

```c++
[ 90%] Built target mstch
Scanning dependencies of target xmrblocks
[ 95%] Building CXX object CMakeFiles/xmrblocks.dir/main.cpp.o
make[2]: *** No rule to make target 'Xmr_WALLET_LIBRARY-NOTFOUND', needed by 'xmrblocks'.  Stop.
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/xmrblocks.dir/all' failed
make[1]: *** [CMakeFiles/xmrblocks.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by moneroexamples** [comment]
Did you build monero using `USE_SINGLE_BUILDDIR=1 make` as shown in readme: https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/devel#compilation-on-ubuntu-16041804 ?

**Comment by normoes** [comment]
Well, it turns out I forgot it.
I didn't take a look at the README again after changing to the `devel`. 
My bad... sorry.

It builds to the end, but shows some warnings:
```
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../x86_64-linux-gnu/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../x86_64-linux-gnu/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
```

But I can start `xmrblocks` and everything works fine :)

**Comment by normoes** [comment]
I close the issue.

**Comment by moneroexamples** [comment]
Cool. No problem.

**Comment by 1986webdeveloper** [comment]
I have facing the same issue as above , also I have tried `USE_SINGLE_BUILDDIR=1 make` for my monero build. Monero is successfully running with `./bin/monerod` command after successfull compilation. The issue is with onion explorer,

Here I have tried few commands,

`cmake -DMONERO_DIR=/home/ubuntu/monero/ -DBOOST_ROOT=/home/ubuntu/boost_1_70_0/  ..`
`cmake -DMONERO_DIR=/home/ubuntu/monero/ ..`

I am getting the same below error,

`CMakeFiles/xmrblocks.dir/build.make:62: recipe for target 'CMakeFiles/xmrblocks.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/xmrblocks.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/xmrblocks.dir/all' failed
make[1]: *** [CMakeFiles/xmrblocks.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

Also I am getting this error as well in ,

`/home/ubuntu/monero/src/blockchain_db/blockchain_db.h:1392:16: note:   no known conversion for argument 1 from ‘const uint64_t {aka const long unsigned int}’ to ‘const epee::span<const long unsigned int>&’
In file included from /home/ubuntu/onion-monero-blockchain-explorer/main.cpp:4:0:
/home/ubuntu/onion-monero-blockchain-explorer/src/page.h:6579:59: error: no match for ‘operator=’ (operand types are ‘std::vector<long unsigned int, std::allocator<long unsigned int> >’ and ‘std::vector<std::vector<long unsigned int, std::allocator<long unsigned int> > >’)
                     .get_tx_amount_output_indices(tx_index);
                                                           ^
In file included from /usr/include/c++/6/vector:69:0,
`
Appreciate your help on this.

**Comment by moneroexamples** [comment]
If you are using development branch of monero (i.e., its current `master` branch), you need to use `devel` branch of the explorer (https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/devel)

**Comment by 1986webdeveloper** [comment]
I have checkout `devel` branch , now I am getting the below error while `make`,

`make[2]: *** No rule to make target 'Xmr_WALLET_LIBRARY-NOTFOUND', needed by 'xmrblocks'.  Stop.`
`CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/xmrblocks.dir/all' failed`
`make[1]: *** [CMakeFiles/xmrblocks.dir/all] Error 2`
`Makefile:83: recipe for target 'all' failed`

 Appreciate your help on this.
make: *** [all] Error 2

**Comment by moneroexamples** [comment]
Need to get back to basics. What monero version are you using? Which branch? Monero must be compiled with `USE_SINGLE_BUILDDIR=1 make` flag for use in any moneroexamples project. Also if monero is not placed in its default directory `~/monero`, then you need to specify where it is to the explorer, using `cmake -DMONERO_DIR=/path/to/monero ..` before you build it.

**Comment by 1986webdeveloper** [comment]
I am using monero latest version from here `https://github.com/monero-project/monero`
Branch is `master`

Also here are the commands I am using to build monero,

`git clone --recursive https://github.com/monero-project/monero.git
`cd monero && git submodule init && git submodule update`
`cmake .. /home/ubuntu/monero2/ -DBOOST_ROOT=/home/ubuntu/boost_1_70_0/`
`make clean`
`USE_SINGLE_BUILDDIR=1 make`

For onion explorer `devel` branch,

`git clone https://github.com/moneroexamples/onion-monero-blockchain-explorer.git`
`cd onion-monero-blockchain-explorer`
`mkdir build && cd build`
`cmake -DMONERO_DIR=/home/ubuntu/monero/ ..`
`make`

Getting the same error ,

`make[2]: *** No rule to make target 'Xmr_WALLET_LIBRARY-NOTFOUND', needed by 'xmrblocks'. Stop.`

**Comment by moneroexamples** [comment]
maybe this is the cause. for monero you use `/home/ubuntu/monero2/` while for the explorer you have `/home/ubuntu/monero` ?

**Comment by 1986webdeveloper** [comment]
Nope , that's not cause , I am using `monero` folder , `monero2` was typo.

**Comment by moneroexamples** [comment]
In that case  I think that your build procedure for monero is incorrect. Normally it should result in `build` folder will all the monero libraries and executables. So the explorer is looking for `/home/ubuntu/monero/build/` which would be produced if you used regular monero compilation procedure. 

The regular procedure is outlined here: https://github.com/moneroexamples/monero-compilation/blob/master/README.md or https://github.com/monero-project/monero#build-instructions  Please note that the procedure does not involved calling `cmake` as everything is already pre-configured in monero. Your execution of `cmake` breaks this configuration in my view. Also newest boost is not needed for monero, if you worry about that.

**Comment by ChrisCharrison** [comment]
@1986webdeveloper @moneroexamples Did you find a fix eventually? I am getting the same error.

I recently read that your master branch, develop branch are both broken, so I'm following the advice to check out v0.14.1.2 in ~/monero and 5e7e90b9f60e1afcb2da0b2dba7f8014ea4418b4 in ~/onion-monero-blockchain-explorer as suggested in

[https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/192#issuecomment-542591172](url)

Compilation of Monero: USE_SINGLE_BUILDDIR=1 make
Compilation of explorer: make

I'm using ubuntu 18.04, OpenSSL 1.1.1  11 Sep 2018, Unbound 1.6.7-1ubuntu2.2, boost 1.65.

I have tried doing make cleans etc to ensure nothing is cached.

**Comment by normoes** [comment]
@ChrisCharrison Please check this issue.
https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/192

**Comment by ChrisCharrison** [comment]
I quoted #192 in my post. That doesn't work. 

> I recently read that your master branch, develop branch are both broken, so I'm following the advice to check out v0.14.1.2 in ~/monero and 5e7e90b in ~/onion-monero-blockchain-explorer as suggested in https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/192#issuecomment-542591172

**Comment by ChrisCharrison** [comment]
The same error as the OP. I will clone everything fresh and do the steps again slowly one by one to confirm that ^

> Sorry.
> 
> Is there a specific error message?
> 
> I think the binary path should be`build/release/bin` instead of just `/bin`, when building with
> 
> ```
> USE_SINGLE_BUILDDIR=1 make
> ```

**Comment by moneroexamples** [comment]
What OS and getting error messages? 

Also need to use `devel` branch of the explorer (https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/devel) with monero's `master` branch.
