### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#1]
so, im on ubuntu 14.04 , I can compile monero, but managed to update gcc to 6, but still get an error

bob@monkey-desktop:~/onion-monero-blockchain-explorer$ make
Scanning dependencies of target mstch
[  6%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/state/in_section.cpp.o
[ 12%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/state/outside_section.cpp.o
[ 18%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/mstch.cpp.o
[ 25%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/render_context.cpp.o
[ 31%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/template_type.cpp.o
[ 37%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/token.cpp.o
[ 43%] Building CXX object ext/mstch/src/CMakeFiles/mstch.dir/utils.cpp.o
Linking CXX static library libmstch.a
[ 43%] Built target mstch
[ 50%] Building CXX object ext/CMakeFiles/myext.dir/format.cc.o
[ 56%] Building CXX object ext/CMakeFiles/myext.dir/dateparser.cpp.o
Linking CXX static library libmyext.a
[ 56%] Built target myext
[ 62%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
In file included from /home/bob/onion-monero-blockchain-explorer/src/MicroCore.h:10:0,
                 from /home/bob/onion-monero-blockchain-explorer/src/MicroCore.cpp:5:
/home/bob/onion-monero-blockchain-explorer/src/monero_headers.h:12:27: fatal error: net/http_base.h: No such file or directory
 #include "net/http_base.h"
                           ^
compilation terminated.
make[2]: *** [src/CMakeFiles/myxrm.dir/MicroCore.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/myxrm.dir/all] Error 2
make: *** [all] Error 2
bob@monkey-desktop:~/onion-monero-blockchain-explorer$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.1.1-3ubuntu11~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=gcc4-compatible --disable-libstdcxx-dual-abi --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.1.1 20160511 (Ubuntu 6.1.1-3ubuntu11~14.04.1)
bob@monkey-desktop:~/onion-monero-blockchain-explorer$

**Comment by Gingeropolous** [comment]
Found the headers from here:
https://github.com/moneroexamples/compile-monero-09-on-ubuntu-16-04

But now compile gives a new error. This is on gcc 6.1.1


In file included from /home/bob/onion-monero-blockchain-explorer/src/page.cpp:5:0:
/home/bob/onion-monero-blockchain-explorer/src/page.h: In member function ‘std::string xmreg::page::show_tx(std::string, uint)’:
/home/bob/onion-monero-blockchain-explorer/src/page.h:1082:71: error: no matching function for call to ‘cryptonote::BlockchainDB::get_tx_amount_output_indices(crypto::hash&)’
                                 .get_tx_amount_output_indices(txd.hash);
                                                                       ^
In file included from /opt/bitmonero-dev/headers/src/cryptonote_core/blockchain.h:56:0,
                 from /home/bob/onion-monero-blockchain-explorer/src/monero_headers.h:19,
                 from /home/bob/onion-monero-blockchain-explorer/src/page.h:16,
                 from /home/bob/onion-monero-blockchain-explorer/src/page.cpp:5:
/opt/bitmonero-dev/headers/src/blockchain_db/blockchain_db.h:1191:33: note: candidate: virtual std::vector<long unsigned int> cryptonote::BlockchainDB::get_tx_amount_output_indices(uint64_t) const
   virtual std::vector<uint64_t> get_tx_amount_output_indices(const uint64_t tx_id) const = 0;
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/bitmonero-dev/headers/src/blockchain_db/blockchain_db.h:1191:33: note:   no known conversion for argument 1 from ‘crypto::hash’ to ‘uint64_t {aka long unsigned int}’
In file included from /home/bob/onion-monero-blockchain-explorer/src/page.cpp:5:0:
/home/bob/onion-monero-blockchain-explorer/src/page.h:1095:34: error: ‘class cryptonote::BlockchainDB’ has no member named ‘get_tx_output_indices’; did you mean ‘get_tx_amount_output_indices’?
                                 .get_tx_output_indices(txd.hash);
                                  ^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/myxrm.dir/page.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/myxrm.dir/all] Error 2
make: *** [all] Error 2

**Comment by moneroexamples** [comment]
monero will not compile on gcc 6. I and others already made a pull request fixing the issues for gcc 6.1.

- https://github.com/monero-project/bitmonero/pull/846

You would need to make a patch from the pull request yourself if you want to compile on gcc 6.1 if you dont want to wait till it will be merged to monero.

**Comment by moneroexamples** [comment]
Btw, if you want to test the onion monero blockchain explorer its already avaliable for testing at: http://xmrblockrjkbt54e.onion/ 

No need to compile it yourself.

**Comment by Gingeropolous** [comment]
Thanks for the responses. 

I'm trying to compile it so I can package it into the Monerodo OS - IMO, everyone should have their own block explorer.

So I switched to gcc 5 , monero compiles again, but the block explorer won't. 

In file included from /home/bob/onion-monero-blockchain-explorer/src/page.cpp:5:0:
/home/bob/onion-monero-blockchain-explorer/src/page.h: In member function ‘std::string xmreg::page::show_tx(std::string, uint)’:
/home/bob/onion-monero-blockchain-explorer/src/page.h:1082:71: error: no matching function for call to ‘cryptonote::BlockchainDB::get_tx_amount_output_indices(crypto::hash&)’
                                 .get_tx_amount_output_indices(txd.hash);
                                                                       ^
In file included from /opt/bitmonero-dev/headers/src/cryptonote_core/blockchain.h:56:0,
                 from /home/bob/onion-monero-blockchain-explorer/src/monero_headers.h:19,
                 from /home/bob/onion-monero-blockchain-explorer/src/page.h:16,
                 from /home/bob/onion-monero-blockchain-explorer/src/page.cpp:5:
/opt/bitmonero-dev/headers/src/blockchain_db/blockchain_db.h:1191:33: note: candidate: virtual std::vector<long unsigned int> cryptonote::BlockchainDB::get_tx_amount_output_indices(uint64_t) const
   virtual std::vector<uint64_t> get_tx_amount_output_indices(const uint64_t tx_id) const = 0;
                                 ^
/opt/bitmonero-dev/headers/src/blockchain_db/blockchain_db.h:1191:33: note:   no known conversion for argument 1 from ‘crypto::hash’ to ‘uint64_t {aka long unsigned int}’
In file included from /home/bob/onion-monero-blockchain-explorer/src/page.cpp:5:0:
/home/bob/onion-monero-blockchain-explorer/src/page.h:1095:34: error: ‘class cryptonote::BlockchainDB’ has no member named ‘get_tx_output_indices’
                                 .get_tx_output_indices(txd.hash);
                                  ^
make[2]: *** [src/CMakeFiles/myxrm.dir/page.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/myxrm.dir/all] Error 2
make: *** [all] Error 2
bob@monkey-desktop:~/onion-monero-blockchain-explorer$

**Comment by moneroexamples** [comment]
Ah ok. 

I see now what is happening. Newest monero version introduced changes to some of its c++ libraries, and it broke the explorer. I already patched the explorer so that it compiles.

However, the changes in monero require me to re-sync the blockchain as they are incompatible with the previous version. So I cant test the explorer if it works now with the changes.

But please know that even if it compiles and run, it will not work it in its full capacity as the search functionality depends on availability of the custom database https://github.com/moneroexamples/lmdbcpp-monero which must be run alongside of the deamon. Now I dont know if it works due to the new changes in monero code. I need to check if lmdbcpp-monero is not broken now as well.

Also the onion explorer depends on a minor change to the deamon itself, which provides some functionality for mempool, which official monero deamon does not. During the development of the onion explorer it was faster to change the monero daemon than to look for workarounds to what I wanted to do in the onion explorer. I need time to make it work with the "official" daemon.

**Comment by Gingeropolous** [comment]
Ok cool thanks for the explanation. Its nice to know whether the code doesn't work because it doesn't work vs. me being a complete knucklehead with this stuff.
