### ISSUE TITLE
Cannot build with monero v0.14.1.2

### ISSUE THREAD

**Issue by normoes** [moneroexamples/onion-monero-blockchain-explorer#192]
I build `monero v0.14.1.2` with the `master` branch of this repository.

This used to work 2 months ago.
Now, it says, when starting to build the blockchain explorer:
```
Scanning dependencies of target mycrypto
[  4%] Building C object src/crypto/CMakeFiles/mycrypto.dir/rx-slow-hash.c.o
/data/onion-monero-blockchain-explorer.git/src/crypto/rx-slow-hash.c:38:10: fatal error: randomx.h: No such file or directory
 #include "randomx.h"
          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [src/crypto/CMakeFiles/mycrypto.dir/build.make:63: src/crypto/CMakeFiles/mycrypto.dir/rx-slow-hash.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:318: src/crypto/CMakeFiles/mycrypto.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by normoes** [comment]
I always forget, and I even made a note to myself, that shortly before a hardfork I should use `devel`.

Is that the case @moneroexamples?

**Comment by moneroexamples** [comment]
Will check this. What linux distro? 

And yes, `devel` is the most recent version of the explorer.

**Comment by normoes** [comment]
This commit (`5e7e90b9f60e1afcb2da0b2dba7f8014ea4418b4`) is building fine with monero `master`.

I build it using docker, it's `debian/stable:slim`.

**Comment by moneroexamples** [comment]
I checked on docker debial-slim image and can't replicate the issue. Are sure you are running latest monero? It does not even compile at present, unless you manually apply this patch: https://github.com/monero-project/monero/pull/5988 

For compilation of the latest monero master branch, I used these instructions: 

https://github.com/moneroexamples/monero-compilation/blob/master/README.md#example-compilation-of-master-branch-ie-development-version-of-monero-on-ubuntu-1804

Also make sure to be on `devel` branch of the explorer. You can use the following command after cloning the explorer

```
git checkout --track origin/devel
```

**Comment by normoes** [comment]
What I want to do is build the blockchain explorer on `master` with monero `v0.14.1.2`.

That's what I used to do.

Compiling the blcokchain explorer on `devel` with monero `master` is wokring just fine.

**Comment by moneroexamples** [comment]
Ah i see. Have to use `devel` for now. `master` branch of the explorer is messed up right now. Sorry.

**Comment by normoes** [comment]
I understand. The problem isthat `develop` already seems to requrie `reandom.h` and `hardfork.h`.

So they don't work with `devel`, I tried that as well.

My solution for now is to checkout `5e7e90b9f60e1afcb2da0b2dba7f8014ea4418b4` and build based on that in combinaion with monero `v0.14.1.2`.

**Comment by moneroexamples** [comment]
In `devel` there is already code for `randomx` in preparation for november hf. 

I think what you do is best solution for now. I check now, `master` is messed up now. It has PR merged which should not be there (got merged by mistake), etc.

**Comment by normoes** [comment]
That's OK. Good luck with everything!

Should we leave this open for now, if anyone had the same problem?

**Comment by moneroexamples** [comment]
Thanks. `randomx` is big change for everyone.
